### ISSUE TITLE
Permissions are ignored for COPY commands

### ISSUE THREAD

**Issue by jrandall** [wtsi-hgi/thrifty-builder#9]
The permissions of the source being COPY'd do not seem to factor in to the hash calculation.

**Comment by colin-nolan** [comment]
True: https://github.com/wtsi-hgi/thrifty-builder/blob/master/thriftybuilder/checksums.py#L54-L56.

**Comment by colin-nolan** [comment]
Fixed by 050569c81d6d4d22338565210874be9cdf710af4.

The downside to this change is that it will generate new checksums for everything, leading to rebuilds across the board. I considered only throwing the permission into the hasher if it was not "normal" (possibly saving on the rebuilds) but I don't think the addition of odd complexity would be worth it.

**Comment by colin-nolan** [comment]
Full fix (that considers changes to directory permissions) is blocked on https://github.com/wtsi-hgi/thrifty-builder/issues/10.

**Comment by colin-nolan** [comment]
Pending merge to `master`
